### ISSUE TITLE
Reporter only sends OPTIONS request, never POST

### ISSUE THREAD

**Issue by JonasVerhofste** [ewhauser/angular-tracing#11]
When running the demo, i.e. after `yarn install` and `yarn quick`, the reporter only ever sends OPTIONS request to zipkin, running on localhost:9411. The returning status code is 200, but since there's never actually any data going out (there never is a POST request), no spans appear, zipkin stays empty. I noticed the same thing when trying to implement this library in an application of my own.

Not sure if it's a problem with zipkin-js itself, this library or if I'm doing something stupid. Tried zipkin (and http-transporter) version 0.14.3, 0.16.0 and 0.17.1, all with the same effect.

**Comment by ewhauser** [comment]
Can you share the response headers from the `OPTIONS` request? Sounds like a CORS issue. The version of the Zipkin server docker container isn't pinned, so it is possible there was a change in behavior there.

**Comment by JonasVerhofste** [comment]
I don't think it's a problem with the container, but with the library, or the upstream zipkin-js library. `zipkin:9411/api/v2/spans` expects a POST-request, as far as I know, but the demo application in both Firefox and Chromium sends an OPTIONS instead.

```
Method: OPTIONS
URL: http://localhost:9411/api/v2/spans
Host: localhost:9411
User-Agent: Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: */*
Accept-Language: en-GB;q=0.5
Accept-Encoding: gzip, deflate
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Referer: http://localhost:4200/heroes
Origin: http://localhost:4200
DNT: 1
Connection: keep-alive
```

**Comment by adriancole** [comment]
hmm we don't see an allow header here. should we cc @trustin

**Comment by adriancole** [comment]
here it looks like if CORS is in place we don't.. https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS

**Comment by JonasVerhofste** [comment]
Seems like CORS is in place indeed https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#cors-cross-origin-resource-sharing
Seeing as Zipkin accepts all requests by default, seems like a problem on the implementation-end.

**Comment by adriancole** [comment]
to be fair, it could be that the http client library is looking for a specific "Allow" or "Access-Control-Request-Method" header... cc also @minwoox

**Comment by trustin** [comment]
> `access-control-allow-methods: GET`

Shouldn't this be `*` or `GET,POST,...`?

**Comment by trustin** [comment]
https://github.com/openzipkin/zipkin/blob/65a0a331c9c97f0dfb596433a5f71782430fcf4d/zipkin-server/src/main/java/zipkin2/server/internal/ZipkinServerConfiguration.java#L90 <- You could specify more methods than just `GET` here.

**Comment by adriancole** [comment]
@trustin that line should be for query.. `zipkin.query.allowed-origins` we only map GET to the /zipkin/api prefix. However, I guess we are missing the right syntax to allow /api/ to do the right thing. Possibly before this was automatic based on annotations.. suggestions?

**Comment by JonasVerhofste** [comment]
Definitely CORS, console gives this error: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:9411/api/v2/spans. (Reason: missing token ‘content-type’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).`
Error is thrown at https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin-transport-http/src/HttpLogger.js#L106

Seems like the server doesn't expect any CORS on /api/v2 or it doesn't 'understand' the request. Like I said: issue should be reproducable by running the example in this repo, should you want extra information.

**Comment by adriancole** [comment]
can you move this issue to openzipkin/zipkin please?

**Comment by JonasVerhofste** [comment]
Gonna close this one, since this wasn't a problem with the library in the first place. Thanks for the help all, and thanks for the fix (https://github.com/openzipkin/zipkin/pull/2489) @adriancole !
