### ISSUE TITLE
Nested local spans

### ISSUE THREAD

**Issue by ewhauser** [ewhauser/angular-tracing#4]
The current implementation of local traces does not allow for nesting of child spans. This can be remedied by adding a stack that tracks the child IDs of the parent span and pops the ID when the span closes.

**Comment by adriancole** [comment]
so you are saying trace.local doesn't nest? https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin/test/trace.test.js#L77

**Comment by ewhauser** [comment]
It might - my challenge is that I can't use `Tracer` implementation of local spans everywhere because the entire interface is callback based. I created a [facade](https://github.com/ewhauser/angular-tracing/blob/master/libs/zipkin/src/lib/local-tracer.ts) for this when I need the pattern, but it's probably not going to be around for very long as it is not a great abstraction.

Let's do an example where we are talking to a GraphQL API since it uses Observables. (incidentally, I don't actually need local span's to trace GraphQL because of the `HttpClient` integration but it serves as a good example).

```typescript
getTableData(tableId: string): Observable<ApolloQueryResult<any>> {
  const result = trace.local('load-table-data', () => {
    return this.loadTableDataGql
      .fetch({
        first: 50,
        tableId,
      })
  }
}
```

Using the facade I wrote, it would look like this:

```typescript
getTableData(tableId: string): Observable<ApolloQueryResult<any>> {
    this.localTracer.startSpan();
    return this.loadTableDataGql
      .fetch({
        first: 50,
        tableId,
      }).pipe(
        tap(res => this.localTracer.stopSpan());
      );
  }
}
```
