### ISSUE TITLE
Aliased class providers

### ISSUE THREAD

**Issue by mauriziocescon** [ewhauser/angular-tracing#46]
It seems to me there is a bug in the definition of the aliased class providers `TRACE_ROOT_TOKEN` / `HTTP_INTERCEPTORS`. 

This is the [official documentation](https://angular.io/guide/dependency-injection-providers#aliased-class-providers) regarding the problem. In my application I get several instances of `LocalTracer` and `ZipkinHttpInterceptor` which causes several side effects. 

On top of this, I think the creation of a span (`startSpan`) should be changed in order to respect the relation child-parent between spans. 

Finally, the [`No arrow functions` issue](https://angular.io/guide/aot-compiler#no-arrow-functions) is related to decorators, not regular ts-code. 

I've created a PR to fix all the points.

**Comment by mauriziocescon** [comment]
I wonder: do you plan to release a new version soon?

**Comment by ewhauser** [comment]
I've published `0.0.16`
