### ISSUE TITLE
Trying to use 0.0.13 shows up as can't find module

### ISSUE THREAD

**Issue by webmutation** [ewhauser/angular-tracing#7]
While doing the import via yarn add @angular-tracing/zipkin zipkin zipkin-transport-http
can't find the module in a angular cli project. 

It's weird because at one point this worked. It seems that the dist is not being published properlly, I see some files that usually are not published in a package and there is a missing index file on the zipkin pacakge, can you check your tsconfig file and see if everything is ok trying to use it in the angular starter app for example.

Also is the readme notice regarding zipkin-transport-http still valid or has it been fixed in 0.16?

**Comment by ewhauser** [comment]
I'm using the latest version of of this in multiple apps. Can you share the error you are getting?

**Comment by ewhauser** [comment]
I'm using Zipkin 0.16.0, but I still have the workarounds in place. Have not tested it without it.

**Comment by webmutation** [comment]
The error I have is can't find module 
`ERROR in src/app/app.module.ts(9,58): error TS2307: Cannot find module '@angular-tracing/zipkin'.`

Because the index.ts file is under the zipkin/src folder, if i move it to the parent /zipkin folder the problem goes away.

The package also has karma.conf.js, tsconfig, yarn-error.log, etc... that probably you don't want to make part of the published dist.

**Comment by ewhauser** [comment]
That shouldn't have been the case - I've published `0.0.14` to correct.
