### ISSUE TITLE
Support for Angular 5.x

### ISSUE THREAD

**Issue by webmutation** [ewhauser/angular-tracing#8]
Any plans to backport to support Angular 5.x?

For example 
```
@Injectable({
  providedIn: 'root'
})
```
not supported in angular 5.x

**Comment by ewhauser** [comment]
Since the current version is Angular 7, I'd rather not back track to support two releases back unless it is small changes to guarantee compatibility. Willing to accept PRs though.

**Comment by webmutation** [comment]
Thanks for your reply. 

5.x is still used a lot and is currently LTS until May 1, 2019
Ok, it should be simply the removal of the new injector and putting it back in the root Providers, also throwError in rxjs was added in 6.x so would need to revert to the previous syntax.

Ill try today to make it work and see if those are the only changes necessary. Unfortunately the project we have is big and we can't migrate anytime soon to 7.x... the platform we provide eui.ecdevop.eu we have 7.x but the project where tracing is still Angular 5.x.

**Comment by webmutation** [comment]
Ok, I tried for a couple of hours to backport, the problem is that now the sample app also has specific issues as well as the version of nx used. in particular ngrx-data is not compatible.

running yarn build:libs works, but I am not able to test it directly and it would not be possible to merge a PR. I did not notice at first that the heros-villains app was also using ng 6.x features.

I really do not want to fork, do you have any suggestions to backport in a more efficient way.

**Comment by ewhauser** [comment]
What are the specific changes needed to support Angular 5 in the library?
If they are relatively small, then I’m not sure we need to have the whole
repo on Angular 5. I will keep those changes in mind until LTS Support for
5 is dropped

**Comment by webmutation** [comment]
Yeah i would like to avoid that as much as possible, our code base is big and migrating to angular 7.x is planned only in about 6 months. Even after 5.x is no longer in LTS :(

In the library it was removal of 
@Injectable({
  providedIn: 'root'
}) 
replaced with @Injectable()
and adding in zipkin.module NgModule
providers: [ZipkinTraceRoot, ZipkinTraceDirective, ZipkinHttpInterceptor]

then replacing in zipkin-http-interceptor.ts 
the import for throwError replaced with 
import { _throw as throwError } from 'rxjs/observable/throw';
and downgrading rxjs to 5.

**Comment by ewhauser** [comment]
The `rxjs` change is a problem for Angular 6+ apps which require `rxjs` 6 I believe. You could add `rxjs-compat` but I don't want to force users to add that just to support this library. Let me know if that is incorrect.

**Comment by webmutation** [comment]
You are absolutely correct. Just had this forward-compat issue after importing the new build.

It's such a nice implementation you did. But I guess I will have to rebuild it with 5.x or reuse what I put together that is only an interceptor.

**Comment by webmutation** [comment]
Hi again... so today I successfully compiled with RXJS 5.5.5 and angular 5.2.11

The changes are really minimal, and are the ones I mentioned. So perhaps you could continue to support both and publish a angular-tracing-5, if not possible let me know. Sorry for being so nagging about this, but we need 5.x compat

**Comment by ewhauser** [comment]
Do you have a suggestion for how to support it in the repository? The problem is that I don't want to force users to use `rxjs-compat` to use this library.

**Comment by webmutation** [comment]
I would create a subfolder with Angular5.x and just place the rxjs 5.5.5 and angular compiler 5.2.11 there and build it as a seperate package. Once Angular 5.x is no longer LTS just not do any more builds unless it's bug fixes. 

I can try to do this next week and do a PR that will not create any conflicts.

**Comment by webmutation** [comment]
We migrated to angular 6.x I backported but it created issues.
